name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password from GitHub Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Use the current directory as the build context
          push: true  # Push the image to Docker Hub
          tags: usrname/wisecow-app:latest  # Tag for the Docker image

  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    needs: build  # This job will wait for the build job to finish successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository

      - name: Set up kubectl
        uses: Azure/setup-kubectl@v1
        with:
          version: 'latest'  # Set up the latest version of kubectl

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig  # Use a GitHub secret for Kubernetes config
          export KUBECONFIG=$PWD/kubeconfig  # Set KUBECONFIG environment variable

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/  # Apply the Kubernetes manifests located in the k8s directory
